# Generated by Django 3.2.4 on 2021-06-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentEntityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('is_disabled', models.BooleanField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('industry_type', models.ManyToManyField(blank=True, null=True, to='accounts.Industry')),
            ],
        ),
    ]
